baseurl                 = "/"
publishDir              = "docs"
languageCode            = "en-us"
defaultContentLanguage  = "en"
isMultilingual          = true
title                   = "Gerald"
pygmentsStyle           = "monokai"               
pygmentsCodefences      = true
# googleAnalytics         = ""             # Tracking code, eg. "UA-111111111-1"

[params]
    dateform            = "Mon Jan 02, 2006"
    dateformfull        = "Mon Jan 2 2006 15:04:05 EST"
    favicon             = "g3.ico"
    homepage            = "main"
    galleryFolder       = "images/"
    clickablePhotos     = false
    smallPreviewImages   = true
    smallImagesSubfolder = "small/"
    footerText          = "www.geraldhspencer.com"

[[params.mainMenu]]
    link = "/about"
    text = "who is gerald?"

[[params.mainMenu]]
    link = "/works"
    text = "Works"
