baseurl                 = "/"
publishDir              = "docs"
languageCode            = "en-us"
defaultContentLanguage  = "en"
isMultilingual          = true
title                   = "Gerald"
pygmentsStyle           = "monokai"               
pygmentsCodefences      = true
googleAnalytics         = "UA-128762731-1"

[params]
    dateform            = "Mon Jan 02, 2006"
    dateformfull        = "Mon Jan 2 2006 15:04:05 EST"
    email               = "ger.spencer3@gmail.com"
    favicon             = "g3.ico"
    footerText          = "www.geraldhspencer.com"
    github_url          = "https://github.com/Geethree"
    homepage            = "main"
    linkedin_url        = "https://www.linkedin.com/in/gerald-spencer-bb2617123/"

[[params.mainMenu]]
    link = "/about"
    text = "who is gerald?"

[[params.mainMenu]]
    link = "/works"
    text = "works"

[[params.mainMenu]]
    text = "blahg"
    url = "https://medium.com/@ger.spencer3"
